name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  integrationtests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: npm install, build, and test
        run: |
          npm install --force
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

  deploy:
    needs: integrationtests
    runs-on: ubuntu-latest
    environment:
      name: Heroku
    steps:
      - name: unzip artifact from build job
        run: unzip release.zip
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: meal-delivery-api
